# Generated by Django 4.2.1 on 2023-05-31 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("items", "0002_item_alter_category_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="print",
            new_name="price",
        ),
        migrations.AddField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="items.category",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="item-images"),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
