# Generated by Django 4.2.1 on 2023-05-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0003_rename_print_item_price_item_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=225),
        ),
    ]
